@host=http://localhost:3333
@token=token

###
GET {{ host }}/v1/categories HTTP/1.1
Authorization: Bearer {{token}}

###
GET {{ host }}/v1/categories/{{ categoryId }} HTTP/1.1
Authorization: Bearer {{token}}

###
POST {{ host }}/v1/categories HTTP/1.1
Authorization: Bearer {{token}}

{
  "slug": "hamburgueria",
  "name": "Hamburgueria",
  "label": "Hamburgueria",
  "description": "This place sells hamburguers",
  "iconName": "hamburguer",
  "iconClasses": "w-4"
}


###
POST {{ host }}/v1/categories HTTP/1.1
Authorization: Bearer {{token}}

{
  "slug": "comida-italiana",
  "name": "Comida Italiana",
  "label": "Comida Italiana",
  "description": "This place sells itallian food",
  "iconName": "comida-italiana",
  "iconClasses": "w-4"
}


###
POST {{ host }}/v1/categories HTTP/1.1
Authorization: Bearer {{token}}

{
  "slug": "lanchonete",
  "name": "Lanchonete",
  "label": "Lanchonete",
  "description": "This place sells lanches",
  "iconName": "lanche",
  "iconClasses": "w-4"
}

###
PUT {{ host }}/v1/categories/lanchonete HTTP/1.1
Authorization: Bearer {{token}}

{
  "name": "Lanchonete",
  "label": "Lanchonete",
  "description": "This place sells lanches",
  "iconName": "lanche",
  "iconClasses": "w-4"
}

###
POST {{ host }}/v1/categories HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "slug": "pizzaria",
  "name": "Pizzari3",
  "label": "Pizzarie",
  "description": "Thiasds place sells pizza",
  "iconName": "pizzarias",
  "iconClasses": "w-4"
}

###

PUT {{ host }}/v1/categories/pizzaria HTTP/1.1
Authorization: Bearer {{token}}

{
  "name": "Pizzaria",
  "name": "Pizzaria",
  "label": "Pizzaria",
  "description": "This place sells pizza",
  "iconName": "pizzaria",
  "iconClasses": "w-4",
  "active": true
}

###
PUT {{ host }}/v1/categories/ISxHJMWcwzxY HTTP/1.1
Authorization: Bearer {{token}}

{
  "active": true
}
