export const defaultCities = [
  {
    id: 1,
    uuid: '631MoVdwcatv',
    name: 'Guarulhos',
    state: 'SP',
    ibgeCode: '3518800',
    country: 'BR',
    label: 'guarulhos',
  },
  {
    id: 2,
    uuid: 'vU2TFimVUMa5',
    name: 'São Paulo',
    state: 'SP',
    ibgeCode: '3550308',
    country: 'BR',
    label: 'sao paulo',
  },
  {
    id: 3,
    uuid: 'ZsEYCGHz54QZ',
    name: 'Paranavaí',
    state: 'PR',
    ibgeCode: '4118402',
    country: 'BR',
    label: 'paranavai',
  },
]

export const defaultTags = [
  {
    uuid: 'yJPSLdrHWe8q',
    slug: 'entrega',
    name: 'Entrega',
    label: 'Entrega',
    description: 'Este lugar oferece serviço de entrega',
    icon: { name: 'delivery' },
  },
  {
    uuid: 'Fk9Yn1onNAcY',
    slug: 'local',
    name: 'Local',
    label: 'Local',
    description: 'Este lugar oferece a opção de comer no local',
    icon: { name: 'dine-in' },
  },
  {
    uuid: '1YoWP6KFIDu1',
    slug: 'cerveja',
    name: 'Cerveja',
    label: 'Cerveja',
    description: 'Este lugar serve cerveja',
    icon: { name: 'beer' },
  },
  {
    uuid: 'iH36HH4ryQdZ',
    slug: 'vegetariano',
    name: 'Vegetariano',
    label: 'Vegetariano',
    description: 'Este lugar serve comida vegetariana',
    icon: { name: 'vegetarian-food' },
  },
  {
    uuid: 'd96GDDbRtojn',
    slug: 'cafe-da-manha',
    name: 'Café da Manhã',
    label: 'Café da Manhã',
    description: 'Este lugar serve café da manhã',
    icon: { name: 'breakfast' },
  },
  {
    uuid: 'n8mdCzX1uJ4N',
    slug: 'brunch',
    name: 'Brunch',
    label: 'Brunch',
    description: 'Este lugar serve brunch',
    icon: { name: 'brunch' },
  },
  {
    uuid: 'q_GPolZbUk2v',
    slug: 'jantar',
    name: 'Jantar',
    label: 'Jantar',
    description: 'Este lugar serve jantar',
    icon: { name: 'dinner' },
  },
  {
    uuid: 's_uVUHyYjE4x',
    slug: 'almoco',
    name: 'Almoço',
    label: 'Almoço',
    description: 'Este lugar serve almoço',
    icon: { name: 'lunch' },
  },
  {
    uuid: 'IufLy0kk66My',
    slug: 'vinho',
    name: 'Vinho',
    label: 'Vinho',
    description: 'Este lugar serve vinho',
    icon: { name: 'wine' },
  },
  {
    uuid: 'IyIUARDLu4OJ',
    slug: 'para-levar',
    name: 'Para Levar',
    label: 'Para Levar',
    description: 'Este lugar oferece a opção de comida para levar',
    icon: { name: 'takeout' },
  },
]

export const defaultCategories = [
  {
    uuid: '0QSkCftpYYaJ',
    slug: 'hamburgueria',
    name: 'Hamburgueria',
    label: 'Hamburgueria',
    description: 'Este lugar serve hamburguers',
    icon: { name: 'hamburguer' },
  },
  {
    uuid: 'OqEHAUF_zFNx',
    slug: 'restaurante',
    name: 'Restaurante',
    label: 'Restaurante',
    description: 'Este lugar é um restaurante',
    icon: { name: 'restaurant' },
  },
  {
    uuid: 'rSjAgDdPjqt_',
    slug: 'steak-house',
    name: 'Steak House',
    label: 'Steak House',
    description: 'Este lugar serve carnes',
    icon: { name: 'steak' },
  },
  {
    uuid: 'VvzC0MuUhwsi',
    slug: 'vegano',
    name: 'Vegano',
    label: 'Vegano',
    description: 'Este lugar serve comida vegana',
    icon: { name: 'vegan' },
  },
  {
    uuid: 'S6qTWitCn138',
    slug: 'pizzaria',
    name: 'Pizzaria',
    label: 'Pizzaria',
    description: 'Este lugar serve pizzas',
    icon: { name: 'pizza' },
  },
  {
    uuid: 'TXXrTMEbglKD',
    slug: 'padaria-e-cafe',
    name: 'Padaria e Café',
    label: 'Padaria e Café',
    description: 'Este lugar serve café e pães',
    icon: { name: 'bread' },
  },
  {
    uuid: 'jm2H8jH92Pr2',
    slug: 'doces-e-sobremesas',
    name: 'Doces e Sobremesas',
    label: 'Doces e Sobremesas',
    description: 'Este lugar serve doces e sobremesas',
    icon: { name: 'dessert' },
  },
  {
    uuid: 'mex8vQSZFWBh',
    slug: 'bares-e-pubs',
    name: 'Bares e Pubs',
    label: 'Bares e Pubs',
    description: 'Este lugar serve bebidas',
    icon: { name: 'beer' },
  },
  {
    uuid: 'z3FQ98BSC2y9',
    slug: 'gastrobar',
    name: 'GastroBar',
    label: 'GastroBar',
    description: 'Este lugar serve bebidas e comida',
    icon: { name: 'beer-food' },
  },
  {
    uuid: 'vPACRNurk5iA',
    slug: 'comida-japonesa',
    name: 'Comida Japonesa',
    label: 'Comida Japonesa',
    description: 'Este lugar serve comida japonesa',
    icon: { name: 'sushi' },
  },
  {
    uuid: 'nWELHes7YQJ1',
    slug: 'comida-italiana',
    name: 'Comida Italiana',
    label: 'Comida Italiana',
    description: 'Este lugar serve comida italiana',
    icon: { name: 'macaroni' },
  },
  {
    uuid: 'Kdjw5LQBVnEj',
    slug: 'comida-nordestina',
    name: 'Comida Nordestina',
    label: 'Comida Nordestina',
    description: 'Este lugar serve comida nordestina',
    icon: { name: 'pan-of-food' },
  },
  {
    uuid: 'SHmeL_a2Nnrn',
    slug: 'lanchonete',
    name: 'Lanchonete',
    label: 'Lanchonete',
    description: 'Este lugar serve lanches',
    icon: { name: 'sandwich' },
  },
]

export default {
  cities: defaultCities,
  tags: defaultTags,
  categories: defaultCategories,
}
