@host=http://localhost:3000
@token=aLJZqrCq3yY$jD3XKUkU8b#GvUYpBjA6bFZBw2au!BS33
@categoryId=pizzarie

###
GET {{ host }}/api/v1/categories HTTP/1.1
Authorization: Bearer {{token}}

###
GET {{ host }}/api/v1/categories/{{ categoryId }} HTTP/1.1
Authorization: Bearer {{token}}

###
POST {{ host }}/api/v1/categories HTTP/1.1
Authorization: Bearer {{token}}

{
  "slug": "hamburgueria",
  "name": "Hamburgueria",
  "label": "Hamburgueria",
  "description": "This place sells hamburguers",
  "iconName": "hamburguer",
  "iconClasses": "w-4"
}

###
POST {{ host }}/api/v1/categories HTTP/1.1
Authorization: Bearer {{token}}

{
  "slug": "pizzarie",
  "name": "Pizzari3",
  "label": "Pizzarie",
  "description": "Thiasds place sells pizza",
  "iconName": "pizzarias",
  "iconClasses": "w-4"
}

###

PUT {{ host }}/api/v1/categories/{{ categoryId }} HTTP/1.1
Authorization: Bearer {{token}}

{
  "name": "Pizzaria",
  "label": "Pizzaria",
  "description": "This place sells pizza",
  "iconName": "pizzaria",
  "iconClasses": "w-4",
  "active": true
}


