@host=http://localhost:3000
@token=aLJZqrCq3yY$jD3XKUkU8b#GvUYpBjA6bFZBw2au!BS33
@id=hamburgeria-do-seu-ze

###
GET http://localhost:3000/api/v1/places
Authorization: Bearer {{token}}

###
POST {{host}}/api/v1/places 
Authorization: Bearer {{token}}

{
  "name": "Hamburgeria do Seu Zé",
  "slug": "hamburgeria-do-seu-ze",
  "description": "O melhor hamburguer da cidade",
  "ratingLevel": 5,
  "ratingCount": 100,
  "pricingLevel": 3,
  "pricingCount": 100,
  "active": true,
  "externalId": "W67inS8LqrDkw",
  "avatar": "ZKvlJ0Kvit2N",
  "cover": "TkFEAWG1BtYS",
  "city": "vU2TFimVUMa5",
  "addressStreet": "Rua dos Bobos",
  "addressNumber": "0",
  "addressComplement": "Apto 1",
  "addressNeighborhood": "Centro",
  "addressZipCode": "00000-000",
  "addressLongitude": -46.633309,
  "addressLatitude": -23.550519,
  "actions": [
    {
      "type": "social",
      "name": "Facebook",
      "link": "https://www.facebook.com/hamburgueriadoseuze",
      "iconName": "facebook",
      "iconClasses": "text-blue-500"
    }
  ],
  "attractions": [
    {
      "uuid": "JBdB995kQ2jm",
      "title": "Attraction 1",
      "description": "Attraction 1 description",
      "mediaId": 1,
      "featured": true,
      "active": true,
      "order": 1,
      "createdAt": "2023-09-20 02:01:33",
      "updatedAt": null
    },
    {
      "id": 6,
      "uuid": "U2NWCJfeFDdA",
      "placeId": 2,
      "title": "Attraction 3",
      "description": "Attraction 3 description",
      "mediaId": 1,
      "featured": true,
      "active": false,
      "order": 1,
      "createdAt": "2023-09-20 23:24:26",
      "updatedAt": null
    }
  ]
}
###
POST {{host}}/api/v1/places 
Authorization: Bearer {{token}}

{
  "name": "Pizzaria do André",
  "slug": "pizzaria-do-andre",
  "description": "A melhor pizza da cidade",
  "ratingLevel": 5,
  "ratingCount": 100,
  "pricingLevel": 3,
  "pricingCount": 100,
  "active": true,
  "externalId": "W67inS8LqrD2w",
  "city": "vU2TFimVUMa5",
  "addressStreet": "Rua dos Bobos",
  "addressNumber": "2",
  "addressComplement": "Apto 1",
  "addressNeighborhood": "Centro",
  "addressZipCode": "00000-000",
  "addressLongitude": -46.633309,
  "addressLatitude": -23.550519,
  "actions": [
    {
      "type": "social",
      "name": "Facebook",
      "link": "https://www.facebook.com/pizzariadoandre",
      "iconName": "facebook",
      "iconClasses": "text-blue-500"
    }
  ]
}


###

PUT {{host}}/api/v1/places/{{id}} HTTP/1.1
Authorization: Bearer {{token}}

{
  "actions": [
    {
      "type": "social",
      "name": "Facebook",
      "link": "https://www.facebook.com/hambugueriadoseuze",
      "iconName": "facebook",
      "iconClasses": "text-blue-500"
    }
  ],
  "categories": ["lanchonete", "hamburgueria"],
  "tags": ["pet-friendly", "vegetarian"]
}

###
GET {{host}}/api/v1/places/{{id}} HTTP/1.1
Authorization: Bearer {{token}}

###
GET {{host}}/api/v1/places/{{id}}/categories HTTP/1.1
Authorization: Bearer {{token}}

###
POST {{host}}/api/v1/places/{{id}}/categories HTTP/1.1
Authorization: Bearer {{token}}

["lanchonete", "hamburgueria"]


###
GET {{host}}/api/v1/places/{{id}}/tags HTTP/1.1
Authorization: Bearer {{token}}

###
POST {{host}}/api/v1/places/{{id}}/tags HTTP/1.1
Authorization: Bearer {{token}}

["pet-friendly", "vegetarian"]

###
GET {{host}}/api/v1/cities HTTP/1.1
Authorization: Bearer {{token}}
